// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: track_order.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ModernTacoShop.TrackOrder.Protos {
  public static partial class TrackOrder
  {
    static readonly string __ServiceName = "modern_taco_shop.TrackOrder";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::ModernTacoShop.TrackOrder.Protos.Order> __Marshaller_modern_taco_shop_Order = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ModernTacoShop.TrackOrder.Protos.Order.Parser));
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::ModernTacoShop.TrackOrder.Protos.OrderId> __Marshaller_modern_taco_shop_OrderId = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ModernTacoShop.TrackOrder.Protos.OrderId.Parser));

    static readonly grpc::Method<global::ModernTacoShop.TrackOrder.Protos.Order, global::Google.Protobuf.WellKnownTypes.Empty> __Method_StartTrackingOrder = new grpc::Method<global::ModernTacoShop.TrackOrder.Protos.Order, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartTrackingOrder",
        __Marshaller_modern_taco_shop_Order,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::ModernTacoShop.TrackOrder.Protos.OrderId, global::ModernTacoShop.TrackOrder.Protos.Order> __Method_GetOrderStatus = new grpc::Method<global::ModernTacoShop.TrackOrder.Protos.OrderId, global::ModernTacoShop.TrackOrder.Protos.Order>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetOrderStatus",
        __Marshaller_modern_taco_shop_OrderId,
        __Marshaller_modern_taco_shop_Order);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_HealthCheck = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HealthCheck",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ModernTacoShop.TrackOrder.Protos.TrackOrderReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TrackOrder</summary>
    [grpc::BindServiceMethod(typeof(TrackOrder), "BindService")]
    public abstract partial class TrackOrderBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> StartTrackingOrder(global::ModernTacoShop.TrackOrder.Protos.Order request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetOrderStatus(global::ModernTacoShop.TrackOrder.Protos.OrderId request, grpc::IServerStreamWriter<global::ModernTacoShop.TrackOrder.Protos.Order> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> HealthCheck(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TrackOrder</summary>
    public partial class TrackOrderClient : grpc::ClientBase<TrackOrderClient>
    {
      /// <summary>Creates a new client for TrackOrder</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TrackOrderClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TrackOrder that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TrackOrderClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TrackOrderClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TrackOrderClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Google.Protobuf.WellKnownTypes.Empty StartTrackingOrder(global::ModernTacoShop.TrackOrder.Protos.Order request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartTrackingOrder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty StartTrackingOrder(global::ModernTacoShop.TrackOrder.Protos.Order request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartTrackingOrder, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> StartTrackingOrderAsync(global::ModernTacoShop.TrackOrder.Protos.Order request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartTrackingOrderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> StartTrackingOrderAsync(global::ModernTacoShop.TrackOrder.Protos.Order request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartTrackingOrder, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::ModernTacoShop.TrackOrder.Protos.Order> GetOrderStatus(global::ModernTacoShop.TrackOrder.Protos.OrderId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrderStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::ModernTacoShop.TrackOrder.Protos.Order> GetOrderStatus(global::ModernTacoShop.TrackOrder.Protos.OrderId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetOrderStatus, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HealthCheck(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HealthCheck(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty HealthCheck(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HealthCheck, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HealthCheckAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HealthCheckAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> HealthCheckAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HealthCheck, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TrackOrderClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TrackOrderClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TrackOrderBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StartTrackingOrder, serviceImpl.StartTrackingOrder)
          .AddMethod(__Method_GetOrderStatus, serviceImpl.GetOrderStatus)
          .AddMethod(__Method_HealthCheck, serviceImpl.HealthCheck).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TrackOrderBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StartTrackingOrder, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ModernTacoShop.TrackOrder.Protos.Order, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.StartTrackingOrder));
      serviceBinder.AddMethod(__Method_GetOrderStatus, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::ModernTacoShop.TrackOrder.Protos.OrderId, global::ModernTacoShop.TrackOrder.Protos.Order>(serviceImpl.GetOrderStatus));
      serviceBinder.AddMethod(__Method_HealthCheck, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.HealthCheck));
    }

  }
}
#endregion
