// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: track_order.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ModernTacoShop.TrackOrder.Protos {

  /// <summary>Holder for reflection information generated from track_order.proto</summary>
  public static partial class TrackOrderReflection {

    #region Descriptor
    /// <summary>File descriptor for track_order.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrackOrderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF0cmFja19vcmRlci5wcm90bxIQbW9kZXJuX3RhY29fc2hvcBobZ29vZ2xl",
            "L3Byb3RvYnVmL2VtcHR5LnByb3RvGhxnb29nbGUvcHJvdG9idWYvc3RydWN0",
            "LnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIiwKBVBv",
            "aW50EhAKCGxhdGl0dWRlGAEgASgJEhEKCWxvbmdpdHVkZRgCIAEoCSJtCg1O",
            "dWxsYWJsZVBvaW50EioKBG51bGwYASABKA4yGi5nb29nbGUucHJvdG9idWYu",
            "TnVsbFZhbHVlSAASKAoFcG9pbnQYAiABKAsyFy5tb2Rlcm5fdGFjb19zaG9w",
            "LlBvaW50SABCBgoEZGF0YSIVCgdPcmRlcklkEgoKAmlkGAEgASgDIoYCCgVP",
            "cmRlchIQCghvcmRlcl9pZBgBIAEoAxIwCgxvcmRlcl9wbGFjZWQYAiABKAsy",
            "Gi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDGxhc3RfdXBkYXRlZBgD",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASPgoVbGFzdF91cGRh",
            "dGVkX3Bvc2l0aW9uGAQgASgLMh8ubW9kZXJuX3RhY29fc2hvcC5OdWxsYWJs",
            "ZVBvaW50EjMKDG9yZGVyX3N0YXR1cxgFIAEoDjIdLm1vZGVybl90YWNvX3No",
            "b3AuT3JkZXJTdGF0dXMSEgoKb3JkZXJfanNvbhgGIAEoCSpqCgtPcmRlclN0",
            "YXR1cxIKCgZQTEFDRUQQABINCglQUkVQQVJJTkcQARIOCgpJTl9UUkFOU0lU",
            "EAISDQoJREVMSVZFUkVEEAMSDQoJQ0FOQ0VMTEVEEAQSEgoOREVMSVZFUllf",
            "RVJST1IQBTLaAQoKVHJhY2tPcmRlchJFChJTdGFydFRyYWNraW5nT3JkZXIS",
            "Fy5tb2Rlcm5fdGFjb19zaG9wLk9yZGVyGhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5EkYKDkdldE9yZGVyU3RhdHVzEhkubW9kZXJuX3RhY29fc2hvcC5PcmRl",
            "cklkGhcubW9kZXJuX3RhY29fc2hvcC5PcmRlcjABEj0KC0hlYWx0aENoZWNr",
            "EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5QiOqAiBNb2Rlcm5UYWNvU2hvcC5UcmFja09yZGVyLlByb3Rvc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ModernTacoShop.TrackOrder.Protos.OrderStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ModernTacoShop.TrackOrder.Protos.Point), global::ModernTacoShop.TrackOrder.Protos.Point.Parser, new[]{ "Latitude", "Longitude" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ModernTacoShop.TrackOrder.Protos.NullablePoint), global::ModernTacoShop.TrackOrder.Protos.NullablePoint.Parser, new[]{ "Null", "Point" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ModernTacoShop.TrackOrder.Protos.OrderId), global::ModernTacoShop.TrackOrder.Protos.OrderId.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ModernTacoShop.TrackOrder.Protos.Order), global::ModernTacoShop.TrackOrder.Protos.Order.Parser, new[]{ "OrderId", "OrderPlaced", "LastUpdated", "LastUpdatedPosition", "OrderStatus", "OrderJson" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum OrderStatus {
    [pbr::OriginalName("PLACED")] Placed = 0,
    [pbr::OriginalName("PREPARING")] Preparing = 1,
    [pbr::OriginalName("IN_TRANSIT")] InTransit = 2,
    [pbr::OriginalName("DELIVERED")] Delivered = 3,
    [pbr::OriginalName("CANCELLED")] Cancelled = 4,
    [pbr::OriginalName("DELIVERY_ERROR")] DeliveryError = 5,
  }

  #endregion

  #region Messages
  public sealed partial class Point : pb::IMessage<Point>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Point> _parser = new pb::MessageParser<Point>(() => new Point());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Point> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ModernTacoShop.TrackOrder.Protos.TrackOrderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point(Point other) : this() {
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point Clone() {
      return new Point(this);
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 1;
    private string latitude_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Latitude {
      get { return latitude_; }
      set {
        latitude_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 2;
    private string longitude_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Longitude {
      get { return longitude_; }
      set {
        longitude_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Point);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Point other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Latitude != other.Latitude) return false;
      if (Longitude != other.Longitude) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Latitude.Length != 0) hash ^= Latitude.GetHashCode();
      if (Longitude.Length != 0) hash ^= Longitude.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Latitude.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Latitude);
      }
      if (Longitude.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Longitude);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Latitude.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Latitude);
      }
      if (Longitude.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Longitude);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Latitude.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Latitude);
      }
      if (Longitude.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Longitude);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Point other) {
      if (other == null) {
        return;
      }
      if (other.Latitude.Length != 0) {
        Latitude = other.Latitude;
      }
      if (other.Longitude.Length != 0) {
        Longitude = other.Longitude;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Latitude = input.ReadString();
            break;
          }
          case 18: {
            Longitude = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Latitude = input.ReadString();
            break;
          }
          case 18: {
            Longitude = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NullablePoint : pb::IMessage<NullablePoint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NullablePoint> _parser = new pb::MessageParser<NullablePoint>(() => new NullablePoint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NullablePoint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ModernTacoShop.TrackOrder.Protos.TrackOrderReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NullablePoint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NullablePoint(NullablePoint other) : this() {
      switch (other.DataCase) {
        case DataOneofCase.Null:
          Null = other.Null;
          break;
        case DataOneofCase.Point:
          Point = other.Point.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NullablePoint Clone() {
      return new NullablePoint(this);
    }

    /// <summary>Field number for the "null" field.</summary>
    public const int NullFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.NullValue Null {
      get { return dataCase_ == DataOneofCase.Null ? (global::Google.Protobuf.WellKnownTypes.NullValue) data_ : global::Google.Protobuf.WellKnownTypes.NullValue.NullValue; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Null;
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ModernTacoShop.TrackOrder.Protos.Point Point {
      get { return dataCase_ == DataOneofCase.Point ? (global::ModernTacoShop.TrackOrder.Protos.Point) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Point;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Null = 1,
      Point = 2,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NullablePoint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NullablePoint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Null != other.Null) return false;
      if (!object.Equals(Point, other.Point)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (dataCase_ == DataOneofCase.Null) hash ^= Null.GetHashCode();
      if (dataCase_ == DataOneofCase.Point) hash ^= Point.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (dataCase_ == DataOneofCase.Null) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Null);
      }
      if (dataCase_ == DataOneofCase.Point) {
        output.WriteRawTag(18);
        output.WriteMessage(Point);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (dataCase_ == DataOneofCase.Null) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Null);
      }
      if (dataCase_ == DataOneofCase.Point) {
        output.WriteRawTag(18);
        output.WriteMessage(Point);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (dataCase_ == DataOneofCase.Null) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Null);
      }
      if (dataCase_ == DataOneofCase.Point) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Point);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NullablePoint other) {
      if (other == null) {
        return;
      }
      switch (other.DataCase) {
        case DataOneofCase.Null:
          Null = other.Null;
          break;
        case DataOneofCase.Point:
          if (Point == null) {
            Point = new global::ModernTacoShop.TrackOrder.Protos.Point();
          }
          Point.MergeFrom(other.Point);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            data_ = input.ReadEnum();
            dataCase_ = DataOneofCase.Null;
            break;
          }
          case 18: {
            global::ModernTacoShop.TrackOrder.Protos.Point subBuilder = new global::ModernTacoShop.TrackOrder.Protos.Point();
            if (dataCase_ == DataOneofCase.Point) {
              subBuilder.MergeFrom(Point);
            }
            input.ReadMessage(subBuilder);
            Point = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            data_ = input.ReadEnum();
            dataCase_ = DataOneofCase.Null;
            break;
          }
          case 18: {
            global::ModernTacoShop.TrackOrder.Protos.Point subBuilder = new global::ModernTacoShop.TrackOrder.Protos.Point();
            if (dataCase_ == DataOneofCase.Point) {
              subBuilder.MergeFrom(Point);
            }
            input.ReadMessage(subBuilder);
            Point = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderId : pb::IMessage<OrderId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderId> _parser = new pb::MessageParser<OrderId>(() => new OrderId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ModernTacoShop.TrackOrder.Protos.TrackOrderReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderId(OrderId other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderId Clone() {
      return new OrderId(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderId other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Order : pb::IMessage<Order>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Order> _parser = new pb::MessageParser<Order>(() => new Order());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Order> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ModernTacoShop.TrackOrder.Protos.TrackOrderReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Order() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Order(Order other) : this() {
      orderId_ = other.orderId_;
      orderPlaced_ = other.orderPlaced_ != null ? other.orderPlaced_.Clone() : null;
      lastUpdated_ = other.lastUpdated_ != null ? other.lastUpdated_.Clone() : null;
      lastUpdatedPosition_ = other.lastUpdatedPosition_ != null ? other.lastUpdatedPosition_.Clone() : null;
      orderStatus_ = other.orderStatus_;
      orderJson_ = other.orderJson_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Order Clone() {
      return new Order(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private long orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OrderId {
      get { return orderId_; }
      set {
        orderId_ = value;
      }
    }

    /// <summary>Field number for the "order_placed" field.</summary>
    public const int OrderPlacedFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp orderPlaced_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp OrderPlaced {
      get { return orderPlaced_; }
      set {
        orderPlaced_ = value;
      }
    }

    /// <summary>Field number for the "last_updated" field.</summary>
    public const int LastUpdatedFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdated {
      get { return lastUpdated_; }
      set {
        lastUpdated_ = value;
      }
    }

    /// <summary>Field number for the "last_updated_position" field.</summary>
    public const int LastUpdatedPositionFieldNumber = 4;
    private global::ModernTacoShop.TrackOrder.Protos.NullablePoint lastUpdatedPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ModernTacoShop.TrackOrder.Protos.NullablePoint LastUpdatedPosition {
      get { return lastUpdatedPosition_; }
      set {
        lastUpdatedPosition_ = value;
      }
    }

    /// <summary>Field number for the "order_status" field.</summary>
    public const int OrderStatusFieldNumber = 5;
    private global::ModernTacoShop.TrackOrder.Protos.OrderStatus orderStatus_ = global::ModernTacoShop.TrackOrder.Protos.OrderStatus.Placed;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ModernTacoShop.TrackOrder.Protos.OrderStatus OrderStatus {
      get { return orderStatus_; }
      set {
        orderStatus_ = value;
      }
    }

    /// <summary>Field number for the "order_json" field.</summary>
    public const int OrderJsonFieldNumber = 6;
    private string orderJson_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderJson {
      get { return orderJson_; }
      set {
        orderJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Order);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Order other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if (!object.Equals(OrderPlaced, other.OrderPlaced)) return false;
      if (!object.Equals(LastUpdated, other.LastUpdated)) return false;
      if (!object.Equals(LastUpdatedPosition, other.LastUpdatedPosition)) return false;
      if (OrderStatus != other.OrderStatus) return false;
      if (OrderJson != other.OrderJson) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId != 0L) hash ^= OrderId.GetHashCode();
      if (orderPlaced_ != null) hash ^= OrderPlaced.GetHashCode();
      if (lastUpdated_ != null) hash ^= LastUpdated.GetHashCode();
      if (lastUpdatedPosition_ != null) hash ^= LastUpdatedPosition.GetHashCode();
      if (OrderStatus != global::ModernTacoShop.TrackOrder.Protos.OrderStatus.Placed) hash ^= OrderStatus.GetHashCode();
      if (OrderJson.Length != 0) hash ^= OrderJson.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OrderId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(OrderId);
      }
      if (orderPlaced_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OrderPlaced);
      }
      if (lastUpdated_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LastUpdated);
      }
      if (lastUpdatedPosition_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LastUpdatedPosition);
      }
      if (OrderStatus != global::ModernTacoShop.TrackOrder.Protos.OrderStatus.Placed) {
        output.WriteRawTag(40);
        output.WriteEnum((int) OrderStatus);
      }
      if (OrderJson.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(OrderJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OrderId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(OrderId);
      }
      if (orderPlaced_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OrderPlaced);
      }
      if (lastUpdated_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LastUpdated);
      }
      if (lastUpdatedPosition_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LastUpdatedPosition);
      }
      if (OrderStatus != global::ModernTacoShop.TrackOrder.Protos.OrderStatus.Placed) {
        output.WriteRawTag(40);
        output.WriteEnum((int) OrderStatus);
      }
      if (OrderJson.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(OrderJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OrderId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OrderId);
      }
      if (orderPlaced_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderPlaced);
      }
      if (lastUpdated_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdated);
      }
      if (lastUpdatedPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdatedPosition);
      }
      if (OrderStatus != global::ModernTacoShop.TrackOrder.Protos.OrderStatus.Placed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OrderStatus);
      }
      if (OrderJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderJson);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Order other) {
      if (other == null) {
        return;
      }
      if (other.OrderId != 0L) {
        OrderId = other.OrderId;
      }
      if (other.orderPlaced_ != null) {
        if (orderPlaced_ == null) {
          OrderPlaced = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        OrderPlaced.MergeFrom(other.OrderPlaced);
      }
      if (other.lastUpdated_ != null) {
        if (lastUpdated_ == null) {
          LastUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastUpdated.MergeFrom(other.LastUpdated);
      }
      if (other.lastUpdatedPosition_ != null) {
        if (lastUpdatedPosition_ == null) {
          LastUpdatedPosition = new global::ModernTacoShop.TrackOrder.Protos.NullablePoint();
        }
        LastUpdatedPosition.MergeFrom(other.LastUpdatedPosition);
      }
      if (other.OrderStatus != global::ModernTacoShop.TrackOrder.Protos.OrderStatus.Placed) {
        OrderStatus = other.OrderStatus;
      }
      if (other.OrderJson.Length != 0) {
        OrderJson = other.OrderJson;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt64();
            break;
          }
          case 18: {
            if (orderPlaced_ == null) {
              OrderPlaced = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OrderPlaced);
            break;
          }
          case 26: {
            if (lastUpdated_ == null) {
              LastUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastUpdated);
            break;
          }
          case 34: {
            if (lastUpdatedPosition_ == null) {
              LastUpdatedPosition = new global::ModernTacoShop.TrackOrder.Protos.NullablePoint();
            }
            input.ReadMessage(LastUpdatedPosition);
            break;
          }
          case 40: {
            OrderStatus = (global::ModernTacoShop.TrackOrder.Protos.OrderStatus) input.ReadEnum();
            break;
          }
          case 50: {
            OrderJson = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt64();
            break;
          }
          case 18: {
            if (orderPlaced_ == null) {
              OrderPlaced = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OrderPlaced);
            break;
          }
          case 26: {
            if (lastUpdated_ == null) {
              LastUpdated = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastUpdated);
            break;
          }
          case 34: {
            if (lastUpdatedPosition_ == null) {
              LastUpdatedPosition = new global::ModernTacoShop.TrackOrder.Protos.NullablePoint();
            }
            input.ReadMessage(LastUpdatedPosition);
            break;
          }
          case 40: {
            OrderStatus = (global::ModernTacoShop.TrackOrder.Protos.OrderStatus) input.ReadEnum();
            break;
          }
          case 50: {
            OrderJson = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
